"""
CIS AWS Foundations Benchmark v1.4 — AWS Config rule mappings.
"""

CIS_RULES: dict = {
    "name": "CIS AWS Foundations Benchmark v1.4",
    "version": "1.4",
    "sections": [
        {
            "id": "CIS1",
            "title": "Identity and Access Management",
            "controls": [
                {
                    "id": "CIS.1.1",
                    "title": "Avoid the use of the root account",
                    "config_rule": "ROOT_ACCOUNT_HARDWARE_MFA_ENABLED",
                    "severity": "CRITICAL",
                    "remediation": "Use IAM roles and users for all operations; enable hardware MFA on root",
                    "remediation_steps": [
                        "Create dedicated IAM admin user for day-to-day operations",
                        "Enable hardware MFA for root account",
                        "Remove root account access keys",
                        "Set up CloudWatch alarm for root account usage",
                    ],
                    "references": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html"],
                },
                {
                    "id": "CIS.1.2",
                    "title": "Ensure MFA is enabled for all IAM users that have a console password",
                    "config_rule": "MFA_ENABLED_FOR_IAM_CONSOLE_ACCESS",
                    "severity": "HIGH",
                    "remediation": "Enable MFA for all console IAM users",
                    "remediation_steps": [
                        "Download credential report from IAM",
                        "Identify users with password_enabled=true and mfa_active=false",
                        "Send enrollment instructions to each user",
                        "Add IAM policy to deny console access without MFA",
                    ],
                    "references": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa.html"],
                },
                {
                    "id": "CIS.1.3",
                    "title": "Ensure credentials unused for 90 days or greater are disabled",
                    "config_rule": "IAM_USER_UNUSED_CREDENTIALS_CHECK",
                    "severity": "MEDIUM",
                    "remediation": "Disable or remove IAM credentials inactive for 90+ days",
                    "remediation_steps": [
                        "Generate IAM Credential Report",
                        "Identify access keys and passwords unused for 90+ days",
                        "Disable or delete unused credentials",
                        "Schedule quarterly credential audits",
                    ],
                    "references": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_finding-unused.html"],
                },
                {
                    "id": "CIS.1.4",
                    "title": "Ensure access keys are rotated every 90 days or less",
                    "config_rule": "ACCESS_KEYS_ROTATED",
                    "severity": "HIGH",
                    "remediation": "Implement automated access key rotation policy",
                    "remediation_steps": [
                        "Use IAM credential report to find keys older than 90 days",
                        "Create new access key, update applications, deactivate old key",
                        "Delete deactivated keys after confirmation",
                        "Automate rotation using Lambda + EventBridge",
                    ],
                    "references": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html"],
                },
                {
                    "id": "CIS.1.5",
                    "title": "Ensure IAM password policy requires minimum length of 14 characters",
                    "config_rule": "IAM_PASSWORD_POLICY",
                    "severity": "MEDIUM",
                    "remediation": "Update account password policy to require 14+ character passwords",
                    "remediation_steps": [
                        "Navigate to IAM → Account Settings → Password Policy",
                        "Set minimum password length to 14",
                        "Enable complexity requirements",
                        "Set password expiry to 90 days, prevent reuse of last 24 passwords",
                    ],
                    "references": ["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_passwords_account-policy.html"],
                },
            ],
        },
        {
            "id": "CIS2",
            "title": "Logging",
            "controls": [
                {
                    "id": "CIS.2.1",
                    "title": "Ensure CloudTrail is enabled in all regions",
                    "config_rule": "CLOUD_TRAIL_ENABLED",
                    "severity": "CRITICAL",
                    "remediation": "Create a multi-region CloudTrail trail",
                    "remediation_steps": [
                        "CloudTrail → Create Trail → enable for all regions",
                        "Enable log file validation",
                        "Store in dedicated encrypted S3 bucket",
                        "Enable CloudWatch integration for real-time alerting",
                    ],
                    "references": ["https://docs.aws.amazon.com/awscloudtrail/latest/userguide/receive-cloudtrail-log-files-from-multiple-regions.html"],
                },
                {
                    "id": "CIS.2.2",
                    "title": "Ensure CloudTrail log file validation is enabled",
                    "config_rule": "CLOUD_TRAIL_LOG_FILE_VALIDATION_ENABLED",
                    "severity": "MEDIUM",
                    "remediation": "Enable log file validation on all CloudTrail trails",
                    "remediation_steps": [
                        "CloudTrail → Trails → select trail → Edit",
                        "Enable 'Log file validation'",
                        "Periodically use aws cloudtrail validate-logs CLI to verify integrity",
                    ],
                    "references": ["https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-log-file-validation-intro.html"],
                },
                {
                    "id": "CIS.2.3",
                    "title": "Ensure AWS Config is enabled in all regions",
                    "config_rule": "CONFIG_ENABLED_IN_REGION",
                    "severity": "HIGH",
                    "remediation": "Enable AWS Config recorder in every active region",
                    "remediation_steps": [
                        "Enable Config in all regions via AWS Organizations or per-region console",
                        "Record all resource types",
                        "Aggregate results in a Config Aggregator",
                        "Set up SNS notifications for Config rule violations",
                    ],
                    "references": ["https://docs.aws.amazon.com/config/latest/developerguide/gs-console.html"],
                },
                {
                    "id": "CIS.2.4",
                    "title": "Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket",
                    "config_rule": "S3_BUCKET_LOGGING_ENABLED",
                    "severity": "MEDIUM",
                    "remediation": "Enable server access logging on CloudTrail S3 buckets",
                    "remediation_steps": [
                        "Go to S3 → CloudTrail bucket → Properties → Server access logging",
                        "Enable logging to a separate target bucket",
                        "Set lifecycle policy to retain logs for 1 year",
                    ],
                    "references": ["https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html"],
                },
            ],
        },
        {
            "id": "CIS3",
            "title": "Monitoring",
            "controls": [
                {
                    "id": "CIS.3.1",
                    "title": "Ensure a log metric filter and alarm exist for unauthorized API calls",
                    "config_rule": "CLOUDWATCH_ALARM_ACTION_CHECK",
                    "severity": "MEDIUM",
                    "remediation": "Create CloudWatch metric filters and alarms for unauthorized API calls",
                    "remediation_steps": [
                        "Create CloudWatch Logs metric filter with pattern: { ($.errorCode = 'AccessDenied') || ($.errorCode = 'UnauthorizedOperation') }",
                        "Create CloudWatch Alarm with threshold > 0",
                        "Set up SNS topic and subscribe security team email",
                        "Test by making a denied API call",
                    ],
                    "references": ["https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html"],
                },
                {
                    "id": "CIS.3.2",
                    "title": "Ensure a log metric filter and alarm exist for Management Console sign-in without MFA",
                    "config_rule": "",
                    "manual_check": "Create CloudWatch Logs metric filter for console logins without MFA",
                    "severity": "HIGH",
                    "remediation": "Create alarm for console sign-ins without MFA",
                    "remediation_steps": [
                        "Create metric filter: { ($.eventName = 'ConsoleLogin') && ($.additionalEventData.MFAUsed != 'Yes') }",
                        "Create alarm with threshold > 0",
                        "Send alert to security team via SNS",
                    ],
                    "references": ["https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html"],
                },
                {
                    "id": "CIS.3.3",
                    "title": "Ensure a log metric filter and alarm exist for root account usage",
                    "config_rule": "",
                    "manual_check": "Create CloudWatch alarm for root account API calls",
                    "severity": "CRITICAL",
                    "remediation": "Create alarm for all root account activity",
                    "remediation_steps": [
                        "Create metric filter: { $.userIdentity.type = 'Root' && $.userIdentity.invokedBy NOT EXISTS && $.eventType != 'AwsServiceEvent' }",
                        "Create alarm with threshold >= 1",
                        "Alert security team and auto-create incident ticket",
                    ],
                    "references": ["https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html"],
                },
            ],
        },
        {
            "id": "CIS4",
            "title": "Networking",
            "controls": [
                {
                    "id": "CIS.4.1",
                    "title": "Ensure no security groups allow ingress from 0.0.0.0/0 to port 22",
                    "config_rule": "INCOMING_SSH_DISABLED",
                    "severity": "CRITICAL",
                    "remediation": "Remove all inbound SSH rules allowing unrestricted access",
                    "remediation_steps": [
                        "List security groups with port 22 open to 0.0.0.0/0",
                        "Remove those inbound rules",
                        "Use AWS Systems Manager Session Manager instead of direct SSH",
                        "Or restrict SSH to specific IP ranges (e.g., VPN CIDR only)",
                    ],
                    "references": ["https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html"],
                },
                {
                    "id": "CIS.4.2",
                    "title": "Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389",
                    "config_rule": "RESTRICTED_INCOMING_TRAFFIC",
                    "severity": "CRITICAL",
                    "remediation": "Remove all inbound RDP rules allowing unrestricted access",
                    "remediation_steps": [
                        "List security groups with port 3389 open to 0.0.0.0/0",
                        "Remove those inbound rules",
                        "Use Systems Manager Fleet Manager for remote Windows access",
                        "Or restrict RDP to VPN CIDR only",
                    ],
                    "references": ["https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html"],
                },
                {
                    "id": "CIS.4.3",
                    "title": "Ensure the default VPC is not in use",
                    "config_rule": "",
                    "manual_check": "Check whether any resources are deployed in the default VPC",
                    "severity": "LOW",
                    "remediation": "Migrate resources from default VPC to custom VPCs and delete the default VPC",
                    "remediation_steps": [
                        "Identify resources in the default VPC",
                        "Migrate to a custom VPC with proper subnetting",
                        "Delete the default VPC once resources are migrated",
                    ],
                    "references": ["https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html"],
                },
            ],
        },
        {
            "id": "CIS5",
            "title": "Storage",
            "controls": [
                {
                    "id": "CIS.5.1",
                    "title": "Ensure S3 Bucket Policy is set to deny HTTP requests",
                    "config_rule": "S3_BUCKET_SSL_REQUESTS_ONLY",
                    "severity": "MEDIUM",
                    "remediation": "Add bucket policy to deny non-HTTPS requests",
                    "remediation_steps": [
                        "For each S3 bucket, add a bucket policy with Condition: aws:SecureTransport: false → Deny",
                        "Use AWS Config remediation to auto-apply the policy",
                    ],
                    "references": ["https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html"],
                },
                {
                    "id": "CIS.5.2",
                    "title": "Ensure S3 buckets have versioning enabled",
                    "config_rule": "S3_BUCKET_VERSIONING_ENABLED",
                    "severity": "LOW",
                    "remediation": "Enable versioning on all S3 buckets containing sensitive data",
                    "remediation_steps": [
                        "S3 → Bucket → Properties → Bucket Versioning → Enable",
                        "Set lifecycle rules to expire old versions after 90 days",
                    ],
                    "references": ["https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html"],
                },
                {
                    "id": "CIS.5.3",
                    "title": "Ensure S3 buckets have MFA Delete enabled",
                    "config_rule": "",
                    "manual_check": "Verify MFA Delete is enabled on buckets with sensitive data",
                    "severity": "MEDIUM",
                    "remediation": "Enable MFA Delete on critical S3 buckets",
                    "remediation_steps": [
                        "Enable versioning first (required for MFA Delete)",
                        "Use CLI with root credentials: aws s3api put-bucket-versioning --bucket BUCKET --versioning-configuration MFADelete=Enabled",
                        "Note: can only be done by root account with physical MFA device",
                    ],
                    "references": ["https://docs.aws.amazon.com/AmazonS3/latest/userguide/MultiFactorAuthenticationDelete.html"],
                },
            ],
        },
    ],
}
